name: deportivo_dart_api
description: "Paquete de apis de deportivo api para app flutter"

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.deportivo_dart_api
    iosBundleIdentifier: com.example.deportivoDartApi
